// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ozworI4keKGP3x12wW9Pel0_seupT-I',
    appId: '1:498878376870:web:63026f60fb37f60eaa7d67',
    messagingSenderId: '498878376870',
    projectId: 'kaamwalijobs-01',
    authDomain: 'kaamwalijobs-01.firebaseapp.com',
    storageBucket: 'kaamwalijobs-01.firebasestorage.app',
    measurementId: 'G-3GKH0MBRVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcXqGTJ0vlGMJrslQ9JofzxvWrmVxYQpg',
    appId: '1:498878376870:android:f4c74727e92875e7aa7d67',
    messagingSenderId: '498878376870',
    projectId: 'kaamwalijobs-01',
    storageBucket: 'kaamwalijobs-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK0_qpo2uEXY77q9tpONeqVSIaDur4uN8',
    appId: '1:498878376870:ios:2ae721303384ab46aa7d67',
    messagingSenderId: '498878376870',
    projectId: 'kaamwalijobs-01',
    storageBucket: 'kaamwalijobs-01.firebasestorage.app',
    iosBundleId: 'com.kaamwalijobs.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK0_qpo2uEXY77q9tpONeqVSIaDur4uN8',
    appId: '1:498878376870:ios:2ae721303384ab46aa7d67',
    messagingSenderId: '498878376870',
    projectId: 'kaamwalijobs-01',
    storageBucket: 'kaamwalijobs-01.firebasestorage.app',
    iosBundleId: 'com.kaamwalijobs.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7ozworI4keKGP3x12wW9Pel0_seupT-I',
    appId: '1:498878376870:web:5d1244f11f7407cdaa7d67',
    messagingSenderId: '498878376870',
    projectId: 'kaamwalijobs-01',
    authDomain: 'kaamwalijobs-01.firebaseapp.com',
    storageBucket: 'kaamwalijobs-01.firebasestorage.app',
    measurementId: 'G-9TJ94246MH',
  );
}
